### ISSUE TITLE
Choosing a management tool

### ISSUE THREAD

**Issue by hiigami** [hiigami/orion#3]
We could use [Projects](https://github.com/hiigami/orion/projects) from github or I found this other options in the marketplace (free for open source projects):
 - [zenhub](https://github.com/marketplace/zenhub)
 - [deepaffects](https://github.com/marketplace/deepaffects)
 - [zube](https://github.com/marketplace/zube)

**Comment by JordyCuan** [comment]
Indeed, using Github/Projects would be a logical choice cuz everything would be only in one place. We don't want to set this project partially on the internet as we can see in other projects that we have, it's my opinion. Zenhub seems to be fancy BTW.
